### ISSUE TITLE
Null-safety migration

### ISSUE THREAD

**Issue by wbusey0** [jeroentrappers/flutter_screenshot_switcher#1]
Migrate the package with null safety support.
Fixable by migrating to flutter 2 in pubspec.yaml

**Comment by wbusey0** [comment]
Hi @jeroentrappers 

Any update on whether you plan to support NNBD for this plugin? I could create a pull-request if you review, merge & publish it.

**Comment by jeroentrappers** [comment]
Yes please make a PR. Thank you!

Op wo 31 mrt. 2021 10:59 schreef wbusey0 ***@***.***>:

**Comment by wbusey0** [comment]
Submitted PR #2

**Comment by jeroentrappers** [comment]
Thanks!
